#!/usr/bin/env bash

# DOOZY-MUSIC - DOOZY-MUSIC

# Copyright (C) 2021-2022 DOOZY-MUSIC

#

# This file is a part of < https://github.com/TEAM-DLK/DOOZY-MUSIC/ >

# PLease read the GNU Affero General Public License in <https://github.com/TEAM-DLK/DOOZY-MUSIC/LICENSE/>.

if [ -d "resources" ]

then

    echo "Current directory Identified.."

else

    apt install git -y

    git clone https://github.com/TEAM-DLK/DOOZY-MUSIC

    cd DOOZY-MUSIC

fi

bash resources/startup/termux.sh
