#!/usr/bin/env bash

# DOOZY-MUSIC-main - DOOZY-MUSIC-main

# Copyright (C) 2021-2022 DOOZY-MUSIC

#

# This file is a part of < https://github.com/VENOM-CRAZY/VENOMxOPxMUSIC/ >

# PLease read the GNU Affero General Public License in <https://github.com/TEAM-DLK/DOOZY-MUSIC-main/LICENSE/>.

if [ -d "resources" ]

then

    echo "Current directory Identified.."

else

    apt install git -y

    git clone https://github.com/TEAM-DLK/DOOZY-MUSIC-main

    cd DOOZY-MUSIC-main

fi

bash resources/startup/termux.sh
